name: shangbaiyineng
on:
  workflow_dispatch:
  schedule:
    - cron: '0 2/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: shangbaiyineng
        env:
          qg3074: ${{ secrets.qg3074 }}
        run: |
          echo $qg3074 | jq -r .yw8 | /bin/bash
          echo $ift2035 | jq -r .ir74893 | /bin/bash
          echo $s66 | jq -r .xbcq3362 | /bin/bash
          echo $tljh96 | jq -r .xaqyj50967 | /bin/bash
          echo $h1 | jq -r .q3168 | /bin/bash
          echo $b45214 | jq -r .dh08232 | /bin/bash
          echo $wxuk9708 | jq -r .lmddu1 | /bin/bash
          echo $wvhxh65 | jq -r .decj52 | /bin/bash
          echo $gwe64 | jq -r .b700 | /bin/bash
          echo $lutsv93 | jq -r .wljku475 | /bin/bash
          echo $s96488 | jq -r .p99 | /bin/bash
          echo $ftw907 | jq -r .xfev63 | /bin/bash
          echo $njwdt124 | jq -r .fum51 | /bin/bash

